### ISSUE TITLE
Missing prototyping on `agent_transform` in NodeJS environment

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#14]
- read through `bleak_agent_tranform` 
- deliverable:
  - unit test of transform functions in NodeJS
     - mocha unit test

**Comment by yehwenting** [comment]
Working on bleak_agent branch

**Comment by foreseaz** [comment]
@yehwenting any updates?

**Comment by yehwenting** [comment]
Tasks are done: set up the unit test environment, read through` bleak_agent_tranform` 

Current Progress: The function is to override bind in order to capture __scope__. Still looking into the codebase to see how __scope__ is being used.

TODO tasks:
- Understand the scenario when the bind and __scope__will be called.
- Unit test cases
- Do NLeak need it? How to implement it with Node Driver

**Comment by foreseaz** [comment]
@foreseaz can also help

**Comment by yehwenting** [comment]
PR https://github.com/nleak/nleak/pull/20
